### ISSUE TITLE
Make map size responsive to container size

### ISSUE THREAD

**Issue by Frijol** [ericnost/streamlit_test#26]
Ideally, we could make the map size responsive to the container size. Currently, the map size is baked in at 400x700 pixels. https://github.com/ericnost/streamlit_test/pull/19/files#diff-b8e16b0e3690a6926fa2ef81aae1ca173ac240a1893a99be2d5bd77c2d809d7aR87

_Originally posted by @ericnost in https://github.com/ericnost/streamlit_test/pull/19#pullrequestreview-1513012479_

**Comment by ericnost** [comment]
Been poking around and this looks like it's not going to be possible since Streamlit has no tool for accessing, via JS, the window properties. 

The best I think that's possible right now is getting rid of the hardcoded height and width and letting the responsiveness built into streamlit do the work. This will resize the map automatically based on different user windows. The downside is that the default map does not fill out the container.
