### ISSUE TITLE
Understanding the EJ map

### ISSUE THREAD

**Issue by Frijol** [ericnost/streamlit_test#30]
How can we make the map and graph clearer here? These are census blocks on the graph & map, right? Why don't they match each other? Why are there so few BLCKGRPCE designations when you click around?

![image](https://github.com/ericnost/streamlit_test/assets/454690/8343e06d-7cf2-4f8c-abcf-d34a13a8f100)

**Comment by ericnost** [comment]
Can you say more - what do you mean they don't match each other (?!)

I think the issue with the BLCKGRPCE designations is that it is an arbitrary identifer from the data that I chose. I think it refers to the # of the block group within a Census tract. There are usually only like 10 block groups within a tract. So, if the box a user draws spans multiple tracts (not shown) then there will likely be many of the same #'d BLKGRPCEs. 

I'm not sure there's another/better identifier. But perhaps we don't need an identifier at all....

**Comment by ericnost** [comment]
Oh right, the charts show the full like 10 digit block identifier, where as the map doesn't. This might have to do with how the data is loaded and joined - it may be that the full 10 digit identifier isn't available when the map is constructed. I'll look into it, but yea, that would be better so that the map and charts would match...
