### ISSUE TITLE
Hierarchies of information: box drawing flow

### ISSUE THREAD

**Issue by Frijol** [ericnost/streamlit_test#6]
I'm finding the flow for analyzing by a specific region a bit unintuitive, curious what our options are. As far as I can tell, the specific subregion needs to be picked once, then pages 2-5 will all load data (but don't need to be in order with respect to each other). I'm trying to think of ways to make it clear in the navigation that pages 2-5 are dependencies of that box-drawing function.

Some ideas:
* Elevate the local area box drawing to the statewide page or even the Welcome page. Or even elevate all the Statewide content as well as the box drawing to the Welcome page?
* Make the pages unclickable unless the box is drawn
* Remove the side-nav bar so that you can only get around based on buttons (I don't really like this option but we can do a lot flow-wise by using the buttons)

**Comment by ericnost** [comment]
> the specific subregion needs to be picked once, then pages 2-5 will all load data (but don't need to be in order with respect to each other

That's right. The user lands on Welcome, navigates to Statewide Overview, and then in SDWA_Violations draws a box that is used to load data for itself, EJ, lead lines, and watershed pollutants.

I am a bit concerned about overloading the Welcome page because I think it could play an important role in situating the user/student. OTOH, giving them something to do on the Welcome page might prove engaging. But what happens after they draw a box on the Welcome page? There would need to be some sort of feedback - what? Maybe they just see the Public Water Systems for that area? Maybe there is no need for an overview of everything? Would help load time. 

I was trying to follow the "overview first, details on demand" approach - start with all water systems, investigate a subset of them + their specifics in what follows.

> Make the pages unclickable unless the box is drawn

That's a great idea, though possibly hard to implement. I did customize error messages such that if you jump to 3-5 without having drawn a box, you're alerted to that fact.

**Comment by ericnost** [comment]
Basically, I like something like:
- Welcome
- Overview of a Selected Place (select the place here, get basic information about it)
- SDWA Violations
- EJ 
- Lead Lines
- Watershed Pollutants

Reminding users that they can return to "Select a place" at any time to investigate violations, EJ, etc. for somewhere else.

**Comment by Frijol** [comment]
This makes sense to me, at least as a reasonable current easiest flow. I will add button references back to the redrawing page so it's easy for users if they want to make a change.
