### ISSUE TITLE
redesign EJ page to include two maps side by side

### ISSUE THREAD

**Issue by ericnost** [ericnost/streamlit_test#73]
One map would show the selected socio-economic indicator and PWS information. The other map would show a selected environmental indicator and PWS information. This would enable more direct EJ insights.

**Comment by ericnost** [comment]
Alternatively, this could be done with a scatter plot, with the x-axis representing SE indicators and the y-axis representing environmental indicators, and the points representing the values of each census block group.

**Comment by ericnost** [comment]
This could also be done as a [bivariate choropleth map](https://www.axismaps.com/guide/bivariate-choropleth) though these can be hard to understand.

**Comment by Frijol** [comment]
Based on the interactions we were watching, I would lean toward the two maps side by side because it seems most intuitive. Our stakeholders are familiar with the locations they are looking at, so the clear visual impression produced by a choropleth overlaid on familiar geography feels like an effective approach.

**Comment by Frijol** [comment]
This is super cool! Couple of issues though: 
* [ ] Maps not draggable/zoomable
* [ ] Color bars are too big, running into the next column (I really want a way for these and the maps to just be 100% width!)
* [ ] The definitions are different sizes, which makes the maps uneven
