### ISSUE TITLE
Consider using color instead of size to indicate SDWA violations

### ISSUE THREAD

**Issue by Frijol** [ericnost/streamlit_test#89]
I'm finding circle size confusing as a "badness" measure. Could we do a scale of lighter to darker red instead to indicate a more severe issue with a given facility on the SDWA page?
![image](https://github.com/ericnost/streamlit_test/assets/454690/22ff2988-cb74-4822-9edf-a9cfb0777aec)

**Comment by Frijol** [comment]
(Should we also show facilities that are not in violation in e.g. blue?)

**Comment by ericnost** [comment]
I think a sequential color scale from white to light red to dark red or equivalent would make sense to show violations as a continuous variable. I wouldn't want to show 0 as a completely separate colour like blue because there is uncertainty as to whether 0 is actually 0 (no inspections, bad reporting, etc.)

**Comment by Frijol** [comment]
I like the new color scale, but the handling of multiple facilities is a bit confusing, especially from a color perspective.

![image](https://github.com/ericnost/streamlit_test/assets/454690/4d419f8b-310d-4c27-a948-83f2c791a3b1)

Could we maye just show the spiral version without needing to click? I think it would give an accurate visual impression of the number of violations in an area. Would be ok to make the circles smaller if that makes this easier.

![image](https://github.com/ericnost/streamlit_test/assets/454690/90231401-cd21-4849-81c8-eeace5a981a6)
