### ISSUE TITLE
Flow more like Jupyter

### ISSUE THREAD

**Issue by Frijol** [ericnost/streamlit_test#9]
I'd really like to sequentialize the interactive components and put markdown between them to make the flow clearer.

**Comment by ericnost** [comment]
So remove the side panel and rely on buttons?

Based on this: https://discuss.streamlit.io/t/is-there-a-way-to-disable-sidebar-for-multipage-navigation-until-main-page-has-finished-loading/35785/2 it might `st.session_state.selboxdisabled = True`

**Comment by Frijol** [comment]
ah, no, I mean within the page! I want to break out these things as three separate sections, e.g.

![image](https://github.com/ericnost/streamlit_test/assets/454690/b662e2f0-1678-4892-8e6e-ee86cb16c382)
 with text between them

**Comment by ericnost** [comment]
Ah, that makes a lot of sense since for the most part there's no linked interactivity between them (clicking on the map doesn't do anything on the charts and vice versa). I think there's a link between the tables (but not the map) in the pollutants section. 

From a technical perspective, I think this would be a matter of removing the `st.columns` calls. I think there are other layout options available: https://docs.streamlit.io/library/api-reference/layout Might be neat to have split rows so that instead of figure text figure text row after row you have figure/text figure/text figure/text together, split as two columns, in each row. An example: https://ericnost.github.io/landloss/index.html
