### ISSUE TITLE
Redesign of lead lines map

### ISSUE THREAD

**Issue by Frijol** [ericnost/streamlit_test#92]
I'm finding the lead lines map challenging to understand. I think there are too many things going on.
![image](https://github.com/ericnost/streamlit_test/assets/454690/05a67f97-5f3c-425e-b48a-6287b4145f0e)
![image](https://github.com/ericnost/streamlit_test/assets/454690/12a79998-8acf-48c9-a3f8-f7ba52cb8cf3)

1. Is the water department itself in violation, in addition to having lead lines? I don't have enough context here. If so, I'm assuming these are different from facility violations?
2. Do we need to show the location of the PWS, or would it be enough to show the service area and number of lead lines? I want to be sure our maps & graphics know what story they are telling, I think this one is just about the number of lead lines
3. On the popup, we should change "Measurement (service lines)" to "Number of lead service lines in area" for clarity
4. It would be nice to have more context about the size of the service area in order to understand the impact of the service lines. Can we show # of people served? Or if all we have is the size category as a proxy, can we remove the other context info (violations, source, type) to keep the focus clearer?

**Comment by ericnost** [comment]
1. Yes, the water department has been in violation of SDWA 12 times since 2001. It's not necessarily due to lead lines, it's just context carried over from other pages. 
2. Yea, we could probably not show the PWS, just the PSA.
3. Excellent
4. I think we might be able to show # of people served yes.

- [ ] Remove PWS
- [ ] Rename Measurement (service lines) column to Number of lead service lines in area
- [ ] Check to see if we have the population served column from the SDWA data - make sure it's joined and display on the popup

**Comment by ericnost** [comment]
We don't have "population served" but we do have system size
