### ISSUE TITLE
Pollutant releases vs violations

### ISSUE THREAD

**Issue by Frijol** [ericnost/streamlit_test#93]
![image](https://github.com/ericnost/streamlit_test/assets/454690/4f1b7aa7-9667-4aa9-9fae-c5733acff850)
on the pollutants page, are these violations, or are some of them scheduled releases of a pollutant? We're naming them all as violations but I suspect some are permitted

**Comment by ericnost** [comment]
Oops, that is a copy/paste error. It should say "the larger the circle, the more reports." 

Note that this metric is different from what is shown in the bar chart (_amount of pollutant_) A lot of that has to do with the fact that some pollutants are measured with different measures so they are hard to compare. This wasn't an issue with the table because it included units, but it becomes tricky in more summary formats like the bar chart and map
